version: '3'
services:
  todolist-mysql:
    image: mysql
    container_name: todolist-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todolist
    volumes:
      - ./migrate.sql:/docker-entrypoint-initdb.d/migrate.sql